/* empty css                      */(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const n=c.closest(".faq-acc-el"),s=n.querySelector(".faq-acc-el-descr-frame"),o=n.querySelector(".faq-img");n.classList.contains("open")?(n.classList.remove("open"),o==null||o.classList.remove("rotated"),s&&(s.style.maxHeight="0")):(n.classList.add("open"),o==null||o.classList.add("rotated"),s&&(s.style.maxHeight=s.scrollHeight+"px"))})});const d=document.querySelectorAll(".navigation-item");d.forEach(c=>{c.addEventListener("click",function(n){n.preventDefault(),d.forEach(s=>s.classList.remove("active")),this.classList.add("active")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),n=c.querySelector(".icon"),s=document.querySelector(".modal"),o=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#E6B456" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#E9FDFD" stroke-linecap="round" />
</svg>
    `,r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#E6B456" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#E9FDFD" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,n.innerHTML=t?r:i,t?a():l()}),o.forEach(f=>f.addEventListener("click",()=>{l(),n.innerHTML=i,t=!1})),window.addEventListener("scroll",u);function a(){s.style.display="block"}function l(){s.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const e=document.getElementById(o);if(!e)return;const t=c(),i=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:i,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",t=>{const i=e.getAttribute("href"),r=i.split("#")[1];(i.startsWith("#")||i.startsWith("index.html#")||i.startsWith("/index.html#"))&&(t.preventDefault(),n(r))})});const o=window.location.hash;if(o){const e=o.substring(1),t=()=>{document.getElementById(e)?n(e):requestAnimationFrame(t)};setTimeout(t,100)}}});document.addEventListener("DOMContentLoaded",function(){const c=document.getElementById("cookie-popup"),n=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(c.style.display="block"),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),c.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),c.style.display="none"})});
//# sourceMappingURL=index.js.map
